package com.phoenix.base.repository2;

import com.phoenix.common.exceptions.SupportException;
import com.phoenix.common.structure.DefaultTuple;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.List;

@SpringBootTest
@ActiveProfiles(value = "dev")
public class AbstractCoreNativeQueryTest {
    @Autowired
    @Qualifier("AbstractCoreNativeQueryImp")
    private AbstractCoreNativeQueryImp coreNativeQueryImp;


    @Test
    public void testExecuteSqlContainMultiExpression() {
        List<?> list = coreNativeQueryImp.executeNativeQuery("select * from fw_user");

        for (Object o : list) {
            //System.out.println(Arrays.toString(o));
            if (o instanceof Object[]) {
                System.out.println(Arrays.toString((Object[]) o));
            } else {
                System.out.println(o);
            }
        }
    }

    @Test
    public void testExecuteSqlSingleExpression() {
        List<?> list = coreNativeQueryImp.executeNativeQuery("select id from fw_user");

        for (Object o : list) {
            System.out.println(o);
        }
    }

    @Test
    public void testExecuteSqlSingleExpression2() {
        List<?> list = coreNativeQueryImp.executeNativeQuery("select id from fw_user where id = 6");

        for (Object o : list) {
            System.out.println(o);
        }
    }

    @Test
    public void testExecuteSqlWithParams() {
        List<?> list = coreNativeQueryImp.executeNativeQuery("select * from fw_user where id < ?", 11);

        for (Object o : list) {
            //System.out.println(Arrays.toString(o));
            if (o instanceof Object[]) {
                System.out.println(Arrays.toString((Object[]) o));
            } else {
                System.out.println(o);
            }
        }
    }

    @Test
    public void testParseResult() throws SupportException {
        List<?> list = coreNativeQueryImp.executeNativeQuery("select id, username, password from fw_user where id < ?", 11);
        DefaultTuple tuple = coreNativeQueryImp.parseResult(list.get(0),
                new String[]{"id", "username", "password"},
                new Class[]{Integer.class, String.class, String.class}
        );

        System.out.println(tuple.get("id", Integer.class));
    }

    @Test
    public void testParseResult2() throws SupportException {
        List<?> list = coreNativeQueryImp.executeNativeQuery("select id, username, password from fw_user where id = ?", 11);
        DefaultTuple tuple = coreNativeQueryImp.parseResult(list.get(0),
                new String[]{"id", "username", "password"},
                new Class[]{Integer.class, String.class, String.class}
        );

        System.out.println(tuple.get("id", Integer.class));
    }

    @Test
    public void testParseResult3() throws SupportException {
        List<?> list = coreNativeQueryImp.executeNativeQuery("select id from fw_user where id = ?", 11);
        DefaultTuple tuple = coreNativeQueryImp.parseResult(list.get(0),
                new String[]{"id"},
                new Class[]{Integer.class}
        );

        System.out.println(tuple.get("id", Integer.class));
    }
}
// Generated by IntelliJ IDEA.
